### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by yongrenjie** [yongrenjie/abbotsbury#1]
### Roadmap

**Major features already in `cygnet`**

- [x] Directory navigation with `cd`
  - [x] "Normal" behaviour with directories
  - [x] `cd -` to return to previous directory
  - [x] Error handling for directories which don't exist
- [x] A command parser for the programme itself
- [x] The `quit` command
- [x] The `help` command
- [x] Switch to (strict?) `Data.Text`
- [x] A representation of the article datatype
- [x] The `read` and `write` commands: interaction with YAML
  - [x] Parsing `cygnet.yaml` (or `abbotsbury.yaml`) into a list of articles
  - [x] Making sure that this is done every time the directory is changed
  - [x] Saving upon exiting the directory / the programme. I think `cygnet`'s backup system has generally been unnecessary.
- [x] The `list` command: pretty-printing articles
- [x] The `open` command: file system management
- [x] The `sort` command
- [x] The `cite` command
- [x] The `add` command
  - [x] Fetching data from Crossref
  - [x] Implementing asynchronous HTTP for multiple requests
- [x] The `delete` command
- [x] The `edit` command
  - [x] Tempfile creation
  - [x] Calling vim (or `$EDITOR`) from inside the program
- [x] The `fetch` command
- [x] The `search` command

**Less important features**
- [ ] The `import` command. Quite rare, my usual workflow is to `add` the DOI, then `fetch` and `open`, rather than to download a PDF from the web. Still, this is helpful with (for example) emailed papers.
- [ ] The `update` command. I don't remember the last time I manually did this.
- [x] Manual PDF management
  - [x] `addpdf`
  - [x] `deletepdf`

**Other stuff**

- [x] `abbot cite` subcommand (right now `cygnet` uses a `cygnet-cite` entry point which is clunky)
- [ ] Other datatypes, particularly...
  - [x] Books
  - [ ] Theses
- [x] Pipes, allowing `search` results to be piped into `cite` (for example). We should plan this ahead of time, and have commands like `search` or `list` return two things: (1) a list of references, (2) text that can be printed to stdout. If it is part of a pipe, then we can pass (1) to the next function, and if not, then we can just print the text.
- [x] Better megaparsec usage, including better command identification and better error reporting.
- [x] A `new` command. This would let us enter metadata manually, and is important for books which have not very good metadata in Crossref.
- [ ] A command for "quick" tagging (technically can be done using `edit`, but we would usually like to tag something without going into vim).
- [ ] A `search_tag` command (abbreviated to `s_tag`, `st`, or similar), which only searches in tags.
- [ ] Let `search` work with acronyms. We can do this crudely by "abbreviating" the title (taking the first letter of each word) and adding it to the haystack.
- [ ] Don't destroy user input from `new` if the parsing fails :-(
- [ ] Modify book to use subtitles as well
